# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 72210935895cb882e19d13147c705fc1ac0905943d5fc0180cff6cbfb6c8c99d9069549c23614252551fce7ace8345be873fb0e072b931ce92063f9796ffbbe5

test:
  secret_key_base: 328cf52985d29de4a2fb4fe836eeb1930e7b7712561521d70fe02221d54620684a6c7b5c60df6140b64f402db1d4be3eed545612520aab13b92d35e9fff97350

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
